spring.application.name=backend

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ep-bold-band-ay51cd34-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IuFDn2Kgh0ZS
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# Server
server.port=8080

# Gemini
gemini.api.key=${GEMINI_API_KEY}